# Generated by Django 4.2.7 on 2026-03-23 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hospitalnews_image_sitesettings_footer_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('current_condition', models.TextField(blank=True)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('UnderObservation', 'Under Observation'), ('Stable', 'Stable'), ('Critical', 'Critical'), ('Closed', 'Closed')], default='Open', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='api.doctor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_cases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_patient_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('current_situation', models.TextField(blank=True)),
                ('follow_up_plan', models.TextField(blank=True)),
                ('encounter_date', models.DateField(default=django.utils.timezone.now)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_encounters', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='api.doctor')),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='api.patientcase')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_encounters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_encounters',
                'ordering': ['-encounter_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted_on', models.DateField()),
                ('discharged_on', models.DateField(blank=True, null=True)),
                ('is_currently_admitted', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admissions', to=settings.AUTH_USER_MODEL)),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='api.patientcase')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_admissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_admissions',
                'ordering': ['-admitted_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='api.patientencounter')),
            ],
            options={
                'db_table': 'prescription_items',
                'indexes': [models.Index(fields=['encounter', 'created_at'], name='prescriptio_encount_b5eb06_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic_number', models.CharField(max_length=50, unique=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('baseline_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_profiles', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to='api.patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_medical_profiles',
                'indexes': [models.Index(fields=['ic_number'], name='patient_med_ic_numb_8f9576_idx'), models.Index(fields=['created_at'], name='patient_med_created_93cdc6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='patientencounter',
            index=models.Index(fields=['patient_case', 'encounter_date'], name='patient_enc_patient_ae8a18_idx'),
        ),
        migrations.AddIndex(
            model_name='patientencounter',
            index=models.Index(fields=['doctor', 'encounter_date'], name='patient_enc_doctor__aae80d_idx'),
        ),
        migrations.AddIndex(
            model_name='patientencounter',
            index=models.Index(fields=['created_at'], name='patient_enc_created_e5eef0_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcase',
            index=models.Index(fields=['patient', 'is_active'], name='patient_cas_patient_4ed292_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcase',
            index=models.Index(fields=['assigned_doctor', 'status'], name='patient_cas_assigne_95415a_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcase',
            index=models.Index(fields=['next_checkup_date'], name='patient_cas_next_ch_8b9eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcase',
            index=models.Index(fields=['created_at'], name='patient_cas_created_93b12b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['patient_case', 'is_currently_admitted'], name='patient_adm_patient_74171b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['admitted_on'], name='patient_adm_admitte_73b553_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['discharged_on'], name='patient_adm_dischar_9b772a_idx'),
        ),
    ]
