# Generated by Django 4.2.7 on 2026-03-09 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hospitalnews_image_sitesettings_footer_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallReceptionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_id', models.CharField(max_length=128, unique=True)),
                ('caller_id', models.CharField(blank=True, default='', max_length=32)),
                ('patient_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('doctor_name', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('appointment_date', models.CharField(blank=True, default='', max_length=32)),
                ('appointment_time', models.CharField(blank=True, default='', max_length=32)),
                ('reason_for_visit', models.TextField(blank=True, default='')),
                ('urgency', models.CharField(blank=True, default='normal', max_length=32)),
                ('confirmation_status', models.CharField(blank=True, default='not_confirmed', max_length=32)),
                ('detected_intent', models.CharField(choices=[('BOOK_APPOINTMENT', 'Book Appointment'), ('CANCEL_APPOINTMENT', 'Cancel Appointment'), ('RESCHEDULE_APPOINTMENT', 'Reschedule Appointment'), ('GENERAL_INQUIRY', 'General Inquiry'), ('HUMAN_HANDOFF', 'Human Handoff'), ('EMERGENCY', 'Emergency')], max_length=32)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('transcript', models.TextField(blank=True, default='')),
                ('extracted_slots', models.JSONField(blank=True, default=dict)),
                ('emergency_flag', models.BooleanField(default=False)),
                ('handoff_flag', models.BooleanField(default=False)),
                ('final_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('escalated', 'Escalated'), ('handoff_requested', 'Handoff Requested'), ('failed_capture', 'Failed Capture')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'call_reception_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='callreceptionrequest',
            index=models.Index(fields=['created_at'], name='call_recep_created_20bffd_idx'),
        ),
        migrations.AddIndex(
            model_name='callreceptionrequest',
            index=models.Index(fields=['detected_intent', 'final_status'], name='call_recep_detecte_896117_idx'),
        ),
        migrations.AddIndex(
            model_name='callreceptionrequest',
            index=models.Index(fields=['caller_id'], name='call_recep_caller__6f0095_idx'),
        ),
    ]
