# Generated by Django 4.2.7 on 2026-03-23 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_callreceptionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('pickup_location', models.TextField()),
                ('condition', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ambulance_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='callreceptionrequest',
            new_name='call_recept_created_773332_idx',
            old_name='call_recep_created_20bffd_idx',
        ),
        migrations.RenameIndex(
            model_name='callreceptionrequest',
            new_name='call_recept_detecte_79fcba_idx',
            old_name='call_recep_detecte_896117_idx',
        ),
        migrations.RenameIndex(
            model_name='callreceptionrequest',
            new_name='call_recept_caller__0e8f6a_idx',
            old_name='call_recep_caller__6f0095_idx',
        ),
    ]
