# Generated by Django 4.2.7 on 2026-03-23 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_seed_patient_cases_from_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('Clinic', 'Clinic'), ('Accident', 'Accident'), ('General', 'General')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_disease',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_otps',
                'indexes': [models.Index(fields=['user', 'created_at'], name='password_re_user_id_b0c36e_idx'), models.Index(fields=['otp_code', 'expires_at'], name='password_re_otp_cod_9ccd05_idx')],
            },
        ),
    ]
