# Generated by Django 4.2.7 on 2026-03-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_patient_patient_type_patient_primary_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
