# Generated by Django 4.2.7 on 2026-03-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_has_changed_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user__full_name']},
        ),
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
    ]
